# Libraries

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# Load Dataset

In [5]:
data_train = pd.read_csv("./dataset/data_train.csv", header=None)
data_test = pd.read_csv("./dataset/data_test.csv", header=None)

In [12]:
data_train

0    1   2    3    4    5    6    7   8   9    10  11   12  13   14  \
0      47  100  27   81   57   37   26    0   0  23   56  53  100  90   40   
1       0   89  27  100   42   75   29   45  15  15   37   0   69   2  100   
2       0   57  31   68   72   90  100  100  76  75   50  51   28  25   16   
3       0  100   7   92    5   68   19   45  86  34  100  45   74  23   67   
4       0   67  49   83  100  100   81   80  60  60   40  40   33  20   47   
...   ...  ...  ..  ...  ...  ...  ...  ...  ..  ..  ...  ..  ...  ..  ...   
7489    0   82   9   59   56   34   41    0  10  30    3  67   42  96  100   
7490   49  100   0   70   24   56  100   65  86  85   44  77   21  38    6   
7491  100   98  60  100   24   87    3   58  35  51   58  26   36   0    0   
7492   59   65  91  100   84   96   72   50  51   8    0   0   45   1  100   
7493    0   78  29  100   94   86   70   48  42  11   32   0   25  36  100   

       15  16  
0      98   8  
1       6   2  
2       0   1  
3       0   4  
4       0   1  
...   ...  ..  
7489  100   5  
7490    0   4  
7491    5   5  
7492    0   1  
7493   40   7  

[7494 rows x 17 columns]

In [11]:
set(data_train[16].values)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

# Random Forest

In [16]:
random_forest = RandomForestClassifier(n_estimators=10, max_depth=3, random_state=0, max_features=3)
random_forest.fit(data_train.drop(columns=[16]), data_train[16])

RandomForestClassifier(max_depth=3, max_features=3, n_estimators=10,
                       random_state=0)

In [29]:
def deep_evaluation(true_list, predict_list):
    """
    Report several evaluation metrics and the confusion matrix
    
    :param true_list: list of true labels
    :param predict_list: list of predict labels
    :return: Nothing
    """
    print(f"Confusion Matrix:\n {confusion_matrix(true_list, predict_list)}")
    print(f"Accuracy = {round(accuracy_score(true_list, predict_list)*100, 2)}%")
    print(f"Recall = {round(recall_score(true_list, predict_list, average='macro')*100, 2)}%")
    print(f"Precision = {round(precision_score(true_list, predict_list, average='macro')*100, 2)}%")
    print(f"F1 = {round(f1_score(true_list, predict_list, average='macro')*100, 2)}%")   

In [30]:
predict_list = random_forest.predict(data_test.drop(columns=[16]))
true_list = data_test[16].values

deep_evaluation(true_list, predict_list)

Confusion Matrix:
 [[312   1   0   0   0   0  15   8  27   0]
 [  0 186 141   2   2   0   0   0   0  33]
 [  0  17 336   5   1   0   0   5   0   0]
 [  0   9   0 324   1   0   0   0   0   2]
 [  0   1   0   1 355   0   0   3   0   4]
 [  0   0   0 109  15 162   7   1   6  35]
 [  2   0   2   4   2   0 292  32   2   0]
 [  0  22  10   2   0   3   0 297   1  29]
 [ 13   0   0   0   0  20  17  43 242   1]
 [  0  90   0  51  23   0   6   1   3 162]]
Accuracy = 76.27%
Recall = 76.04%
Precision = 77.26%
F1 = 75.4%
